apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: sampleapp
  name: sampleapp
spec:
  ports:
    - name: "8080"
      port: 8080
      protocol: TCP
      nodePort: 32323
      targetPort: 8080
  selector:
    io.kompose.service: sampleapp
status:
  loadBalancer: {}
